### ISSUE TITLE
Package to install

### ISSUE THREAD

**Issue by ghost** [Nomanod/ansible-redmine#4]
Hey. In Debian 9 libmysqlclient-dev is called libmariadbclient-dev (though, there is also libmariadbclient-dev for some mysql compatibilities, which I don't think we would need). Should we just move to the libmariadbclient-dev package like this: https://github.com/libraries-fi/ansible-krahser-redmine/commit/927fc548c5e0eb85b96a24e09d152773411a22f6? Or do some distribution version checking?

**Comment by AlMaVizca** [comment]
Hi!

It would be better if we can do some distribution version checking.
Could you do that, please?

Thanks

**Comment by ghost** [comment]
I think actually all the database client packages could be deleted from this role as they are already installed in ANXS.mysql role (the role installs the meta package mysql-client). And so as this role depends on the ANXS.mysql role the PostgreSQL and SQLite client library packages can also be removed.

If this works for you I will send a patch after testing the suggested changes.

**Comment by AlMaVizca** [comment]
Yes, if we can delegate that on another role it's perfect for me.

**Comment by ghost** [comment]
@krahser ping. I made the pull request. It was unfortunately not quite possible to delegate the installation to the another role.

**Comment by ghost** [comment]
Thanks!
